### ISSUE TITLE
编译报错，srs_hijack_io_is_never_timeout方法返回类型不一致

### ISSUE THREAD

**Issue by moon1234** [ossrs/srs-bench#22]
src/app/htl_app_srs_hijack.cpp:105:75: 错误：对‘int srs_hijack_io_is_never_timeout(srs_hijack_io_t, int64_t)’的新声明
 int srs_hijack_io_is_never_timeout(srs_hijack_io_t /*ctx*/, int64_t /*tm*/)

src/app/srs_librtmp.h:1039:17: 错误：使旧的声明‘bool srs_hijack_io_is_never_timeout(srs_hijack_io_t, int64_t)’出现歧义
     extern bool srs_hijack_io_is_never_timeout(srs_hijack_io_t ctx, int64_t timeout_us);

**Comment by winlinvip** [comment]
![image](https://user-images.githubusercontent.com/2777660/74231951-bfb7f980-4d02-11ea-9a57-3da5e4bd36da.png)
