### ISSUE TITLE
sb_rtmp_publish 推理超过300路 播放会卡 

### ISSUE THREAD

**Issue by notedit** [ossrs/srs-bench#6]
几种场景 

一:

sb_rtmp_publish1  推  300路
sb_rtmp_publish2  推  300路

cpu 和 io 都非常低但播放卡

二:

sb_rtmp_publish1  推  1路
sb_rtmp_publish2  推  1500路
sb_rtmp_publish3  推  1500路

播放sb_rtmp_publish1 推的那一路,播放流畅,  

cpu 使用30%左右   

基本可以断定是 srs-bench 推多路流的时候有bug.

**Comment by winlinvip** [comment]
嗯，查查时间戳和sleep机制。

**Comment by harleyxt** [comment]
这个问题解决了吗？我遇到同样的情况

**Comment by notedit** [comment]
可以开很多个ffmpeg来模拟

**Comment by harleyxt** [comment]
> 可以开很多个ffmpeg来模拟
有脚本参考下吗？我自己写了个，只开启了一个ffmpeg,线程被ffmpeg打印信息阻塞了。
