### ISSUE TITLE
st_init 提示失败,请问要怎么解决,我是在mac上测试的

### ISSUE THREAD

**Issue by kivenZheng** [ossrs/srs-bench#9]
st_init failed. ret=400 errno=22(Invalid argument)

**Comment by winlinvip** [comment]
我记得在macOS下跑过，难道新的macOS不支持了？

**Comment by hhdem** [comment]
我也是同样的问题

**Comment by belltoy** [comment]
http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit
